// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMq5m8WqVx4uG1BT2TntAwC8XFY0xK4Qg',
    appId: '1:942989580898:android:c8c83159d6be9477a90f3b',
    messagingSenderId: '942989580898',
    projectId: 'attendance-db5bd',
    storageBucket: 'attendance-db5bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIXQm158l4exO-Cg4PZQBXuRddquFkNYw',
    appId: '1:942989580898:ios:281974533449d61ca90f3b',
    messagingSenderId: '942989580898',
    projectId: 'attendance-db5bd',
    storageBucket: 'attendance-db5bd.appspot.com',
    androidClientId: '942989580898-q5fbui0ja7mfpbu5idgglsbgpin8nfkc.apps.googleusercontent.com',
    iosClientId: '942989580898-it9puvt6t1ocfog37ci64h96cv9ql734.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
